#!/bin/bash
echo -ne "\033[2m"
curl -L#H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36" "$1" > /tmp/Testfile
echo -e "\033[22;0m"
echo -e "\033[1;34mSHA256:\033[22;0m"
shasum -a 256 /tmp/Testfile | awk '{print $1;}'
echo ""
rm /tmp/Testfile
