#!/bin/bash

( [ "$1" = "" ] && echo -e "\033[1;31mPlease specify a package name.\033[22;0m" ) || (([ -e "$(brew --prefix)/Library/Taps/caskroom/homebrew-cask/Casks/$1.rb" ] && cat "$(brew --prefix)/Library/Taps/caskroom/homebrew-cask/Casks/$1.rb" ) || echo -e "\033[1;31mNo such cask '$1'.\033[22;0m")
